version: 1.1.{build}
branches:
  only:
  - master
skip_tags: true
configuration: Release
platform: Any CPU
nuget:
  project_feed: true
artifacts:
- path: '*Platypus*.nupkg'
deploy:
- provider: NuGet
  api_key:
    secure: YPGdPLnY9FEYDZz3zZFV/+BKreynP4W2/DoURr0XlBjS8eLkkSypvEkI0BQSfRur
  artifact: /.*\.nupkg/
  on:
    branch: /master|Development/
