version: 1.1.{build}
branches:
  only:
  - master
skip_tags: true
nuget:
  project_feed: true
build_script:
- ps: nuget -Pack Platypus.Common.Logging.Resharper.Annotations.nuspec      
artifacts:
- path: '*Platypus*.nupkg'
deploy:
- provider: NuGet
  api_key:
    secure: YPGdPLnY9FEYDZz3zZFV/+BKreynP4W2/DoURr0XlBjS8eLkkSypvEkI0BQSfRur
  artifact: /.*\.nupkg/
  on:
    branch: /master|Development/